language: node_js
sudo: false
notifications:
  email: false
node_js:
  - '8'
before_install:
  - export CHROME_BIN=chromium-browser
  - if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
